name: Build Plugin

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: ServerPassword
          path: target/ServerPasswordPlugin-1.0.0.jar
